api {
  # Tan Pham's workspace
  web_server: https://app.clear.ml/
  api_server: https://api.clear.ml
  files_server: https://files.clear.ml
  credentials {
    "access_key" = "DGSOVO7ROLR8K9VB8YDLLL27BW9LTG"
    "secret_key" = "81KGB_iv600Wz0uRnvOftwn-JmaiLFzCT8dYkhnukmQ1wP_UQdgPxWkte0536bpcaaw"
  }
}
